name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          java-version: "24"
          distribution: "temurin"
          cache: maven
          server-id: github-connectrpc-spring-boot
          server-username: GITHUB_ACTOR
          server-password: GH_PACKAGES_PAT
      - name: Build with Maven
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}
        run: ./mvnw -B verify
